<?php $codelink = $block->getUrl('wishlist/shared', ['code' => $block->getSharingCode(), 'whatsapp' => 1]); ?>
<!--
<p><a href="<?php echo $block->escapeUrl($codelink) ?>"><?php echo $codelink ?></a></p>
-->

<form class="form wishlist share"
      action="<?php echo $block->escapeUrl($block->getSendUrl()) ?>"
      id="form-validate"
      method="post"
      data-hasrequired="<?php echo $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field emails required">
            <label class="label" for="email_address"><span><?php echo $block->escapeHtml(__('E-Mail-Adressen für die Einladung, getrennt durch Komma')) ?></span></label>
            <div class="control">
                <textarea name="emails" cols="60" rows="5" id="email_address" data-validate="{required:true,'validate-emails':true}"><?php echo /* @noEscape */ $block->getEnteredData('emails') ?></textarea>
            </div>
        </div>
        <div class="field text">
            <label class="label" for="message"><span><?php echo $block->escapeHtml(__('Einladungstext')) ?></span></label>
            <div class="control">
<textarea id="message" name="message" cols="60" rows="7">
<?php echo __('Liebe Freundinnen und Freunde'); ?>


<?php echo __('Ich mache eine Crowd-Order bei gebana.'); ?>
<?php echo __('Über den Link im E-Mail könnt ihr ebenfalls teilnehmen. Die Lieferung und die Rechnung kommen zu mir, wir organisieren uns dann!'); ?>


<?php echo __('Bis bald'); ?>
</textarea>
            </div>
        </div>
        <?php if ($this->helper('Magento\Wishlist\Helper\Rss')->isRssAllow()): ?>
            <div class="field choice rss">
                <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?php echo $block->escapeHtmlAttr(__('Check here to link an RSS feed to your Wish List.')) ?>" class="checkbox">
                <label class="label" for="rss_url">
                    <span>
                        <?php echo $block->escapeHtml(__('Check here to link an RSS feed to your Wish List.')) ?>
                    </span>
                </label>
            </div>
        <?php endif; ?>
    </fieldset>
    <?php echo $block->getChildHtml('captcha'); ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?php echo $block->escapeHtmlAttr(__('Freunde einladen')) ?>" class="action submit primary">
                <span><?php echo $block->escapeHtml(__('Freunde einladen')) ?></span>
            </button>
            <button title="<?php echo $block->escapeHtmlAttr(__('Teilen')) ?>" class="primary whatsapp" onclick="window.open('https://wa.me/?phone&text='+encodeURIComponent('Liebe Freundinnen und Freunde, ich mache eine Crowd-Order bei gebana. Über den folgenden Link könnt ihr teilnehmen. Die Lieferung und die Rechnung kommen zu mir, wir organisieren uns dann! Bis bald. <?php echo $block->escapeUrl($codelink) ?>'), '_blank')">
                <span><?php echo $block->escapeHtml(__('Teilen')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>

<style>
    .message.success {display:none}
</style>
