<?php

$wishlistItemId = $block->getItem()->getWishlistItemId();
?>
<fieldset class="fieldset info owner-add-participant">
    <div class="field"><label class="label"<span><?php echo __('First Name'); ?></span></label>
        <input type="text" data-name="firstname" class="input-text dinamically senditem" data-required="true">
    </div>
    <div class="field">
        <label class="label"<span><?php echo __('Last Name'); ?></span></label>
        <input type="text" data-name="lastname" class="input-text dinamically senditem"  data-required="true">
    </div>
    <div class="field">
        <label class="label"><span><?php echo __('Email'); ?></span></label>
        <input type="text" data-name="email" class="input-text dinamically senditem"  data-required="false">
    </div>
    <div class="field">
        <label class="label"<span><?php echo __('Quantity'); ?></span></label>
        <input type="number" data-name="qty" class="input-text dinamically senditem qty-validation"  data-required="true">
    </div>
    <div class="field field-comment ">
        <label class="label"><span><?php echo __('Comment'); ?></span></label>
        <textarea data-name="comment" class="input-text dinamically senditem"  data-required="false"></textarea>
        <button class="action save primary wishlist-participant-owner-add" type="submit" title="<?php echo __('Save'); ?>">
            <span><?php echo __('Save'); ?></span>
        </button>
    </div>
    <input type="hidden" data-name="wishlist_item_id" value="<?php echo $wishlistItemId ?>" class="senditem">
 
    <div class="actions-toolbar">
        <div class="primary">

        </div>
    </div>
</fieldset>


<div class="participants" id="participant_list_<?php echo $wishlistItemId ?>">
    <span class="wishlist-participants-title" style="display:none;"><?php echo __('Teilnehmer') ?></span>

    <div class="wishlist-participants-title-empty" style="display:none;">
        <div class="page messages">
            <div role="alert" class="messages">
                <div class="message-notice notice message">
                    <div><?php echo __('An diesem Produkt hat sich bisher niemand beteiligt.') ?></div>
                </div>
            </div>
        </div>
    </div>

    <ul class="wishlist-participants-list" data-wishlistitemid="<?php echo $wishlistItemId ?>" data-code="<?php echo $block->getCode() ?>"></ul>
    <div class="wishlist-participants-total">
        <div class="total_qty"><?php echo __('Verteilte Menge bisher'); ?>: <span>0</span></div>
        <div class="available_qty"><?php echo __('Noch verfügbare Menge'); ?>: <span>0</span></div>
    </div>
</div>

