name: M2 testing Jobs

on:
  push:
    branches: [dev, master]

jobs:
  phpcs:
    name: PHP code sniffer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/code/MediaDivision
    steps:
      - name: "Checkout repository.."
        uses: actions/checkout@v2
      - name: "Testing against Magento2 coding standard.."
        uses: extdn/github-actions-m2/magento-coding-standard@master
