name: M2 testing Jobs

on:
  push:
    branches: [dev, master]

jobs:
  build:
    name: Building Magento 2
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #defaults:
      #run:
        #working-directory: .
    steps:
      - name: "Setting up PHP.." # https://github.com/marketplace/actions/setup-php-action
        uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
        with:
          php-version: "7.3"
          tools: composer:v1
          #extensions:
      - name: "Checkout repository.."
        uses: actions/checkout@v2
      - name: "Installing with composer.."
        run: composer install
      - name: "Creating dummy database.." # https://github.com/marketplace/actions/setup-mysql
        run: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS 'test-magento2';"
      - name: "Copying dummy configuration.."
        run: cp ./app/etc/env.php.tst ./app/etc/env.php
      - name: "Installing Magento's setup.."
        run: bin/magento setup:install
      - name: "Upgrading Magento's setup.."
        run: bin/magento setup:upgrade
      - name: "Compiling Magento's code.."
        run: bin/magento setup:di:compile;
      - name: "Deploying static content.."
        run: bin/magento setup:static-content:deploy;
  phpcs:
    name: PHP Code Sniffer    
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository.."
        uses: actions/checkout@v2
